# Stage 1: Build
FROM node:22-slim AS builder

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install all dependencies (including devDependencies for vinxi build)
RUN npm install

# Copy project files
COPY . .

# Build the project using Vinxi for a Node server environment
# The app.config.ts file tells Vinxi how to build this TanStack Start app
ENV NITRO_PRESET=node-server
ENV NODE_OPTIONS="--max-old-space-size=1536"
RUN npm run build

# Stage 2: Runtime
FROM node:22-slim

WORKDIR /app

# Set production environment
ENV NODE_ENV=production
ENV PORT=3000

# Copy the built output (.output is generated by vinxi build with node-server preset)
COPY --from=builder /app/.output ./.output

# Expose the port
EXPOSE 3000

# Start the server
CMD ["node", ".output/server/index.mjs"]
