/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangIndexRouteImport } from './routes/$lang.index'
import { Route as LangOffersRouteImport } from './routes/$lang.offers'
import { Route as LangFleetRouteImport } from './routes/$lang.fleet'
import { Route as LangContactRouteImport } from './routes/$lang.contact'
import { Route as LangAboutRouteImport } from './routes/$lang.about'
import { Route as LangAirportsTetouanRouteImport } from './routes/$lang.airports.tetouan'
import { Route as LangAirportsTangierRouteImport } from './routes/$lang.airports.tangier'

const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any)
const LangOffersRoute = LangOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => LangRoute,
} as any)
const LangFleetRoute = LangFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => LangRoute,
} as any)
const LangContactRoute = LangContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LangRoute,
} as any)
const LangAboutRoute = LangAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LangRoute,
} as any)
const LangAirportsTetouanRoute = LangAirportsTetouanRouteImport.update({
  id: '/airports/tetouan',
  path: '/airports/tetouan',
  getParentRoute: () => LangRoute,
} as any)
const LangAirportsTangierRoute = LangAirportsTangierRouteImport.update({
  id: '/airports/tangier',
  path: '/airports/tangier',
  getParentRoute: () => LangRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/$lang/about': typeof LangAboutRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/fleet': typeof LangFleetRoute
  '/$lang/offers': typeof LangOffersRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/airports/tangier': typeof LangAirportsTangierRoute
  '/$lang/airports/tetouan': typeof LangAirportsTetouanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/fleet': typeof LangFleetRoute
  '/$lang/offers': typeof LangOffersRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/airports/tangier': typeof LangAirportsTangierRoute
  '/$lang/airports/tetouan': typeof LangAirportsTetouanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/$lang/about': typeof LangAboutRoute
  '/$lang/contact': typeof LangContactRoute
  '/$lang/fleet': typeof LangFleetRoute
  '/$lang/offers': typeof LangOffersRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/airports/tangier': typeof LangAirportsTangierRoute
  '/$lang/airports/tetouan': typeof LangAirportsTetouanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/$lang/about'
    | '/$lang/contact'
    | '/$lang/fleet'
    | '/$lang/offers'
    | '/$lang/'
    | '/$lang/airports/tangier'
    | '/$lang/airports/tetouan'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$lang/about'
    | '/$lang/contact'
    | '/$lang/fleet'
    | '/$lang/offers'
    | '/$lang'
    | '/$lang/airports/tangier'
    | '/$lang/airports/tetouan'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/$lang/about'
    | '/$lang/contact'
    | '/$lang/fleet'
    | '/$lang/offers'
    | '/$lang/'
    | '/$lang/airports/tangier'
    | '/$lang/airports/tetouan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRoute: typeof LangRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/offers': {
      id: '/$lang/offers'
      path: '/offers'
      fullPath: '/$lang/offers'
      preLoaderRoute: typeof LangOffersRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/fleet': {
      id: '/$lang/fleet'
      path: '/fleet'
      fullPath: '/$lang/fleet'
      preLoaderRoute: typeof LangFleetRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/contact': {
      id: '/$lang/contact'
      path: '/contact'
      fullPath: '/$lang/contact'
      preLoaderRoute: typeof LangContactRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/about': {
      id: '/$lang/about'
      path: '/about'
      fullPath: '/$lang/about'
      preLoaderRoute: typeof LangAboutRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/airports/tetouan': {
      id: '/$lang/airports/tetouan'
      path: '/airports/tetouan'
      fullPath: '/$lang/airports/tetouan'
      preLoaderRoute: typeof LangAirportsTetouanRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/airports/tangier': {
      id: '/$lang/airports/tangier'
      path: '/airports/tangier'
      fullPath: '/$lang/airports/tangier'
      preLoaderRoute: typeof LangAirportsTangierRouteImport
      parentRoute: typeof LangRoute
    }
  }
}

interface LangRouteChildren {
  LangAboutRoute: typeof LangAboutRoute
  LangContactRoute: typeof LangContactRoute
  LangFleetRoute: typeof LangFleetRoute
  LangOffersRoute: typeof LangOffersRoute
  LangIndexRoute: typeof LangIndexRoute
  LangAirportsTangierRoute: typeof LangAirportsTangierRoute
  LangAirportsTetouanRoute: typeof LangAirportsTetouanRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangAboutRoute: LangAboutRoute,
  LangContactRoute: LangContactRoute,
  LangFleetRoute: LangFleetRoute,
  LangOffersRoute: LangOffersRoute,
  LangIndexRoute: LangIndexRoute,
  LangAirportsTangierRoute: LangAirportsTangierRoute,
  LangAirportsTetouanRoute: LangAirportsTetouanRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
